name: docker train

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Python dependencies # To run the docker build from tasks, i need python in the github compiler
      run: |
        pip install invoke

    - name: Build Docker image (via invoke)
      run: invoke docker-build --tag=ghcr.io/${{ github.repository }}:latest --progress=plain

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push the Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}:latest

